---
# A list of locale, using the ISO 639-1 2 letters language code (lower case), followed by
# an underscore, followed by the ISO 3166-1 2 letter region (upper case).
#
# For instance: en_GB, fr_FR, ca_ES
string[] locales
